changelog:
  categories:
    - title: Features
      labels: [feature, enhancement]
    - title: Fixes
      labels: [fix, bug]
    - title: Documentation
      labels: [docs]
    - title: CI and build
      labels: [ci, build]
    - title: Other changes
      labels: ["*"]
